---
title: "MY Portfolio"  

---
## Barrier Option Simulated Price
install.packages("reshape2")
library(ggplot2)
library(reshape2)
s=200
interval = 400
t = 0.5/interval
r = 0.03
sigma=0.2
mu = r-0.5*sigma^2
stock = 40
barrier = 50
strike=35

set.seed(1000)

rnd.num = as.data.frame(matrix(rnorm(s*interval),s,interval))
rnd2.num = as.data.frame(matrix(0,s,interval))
BarrierPrice = function(r,sigma) {
for (i in 1: s) {
  for ( j in 1: interval) {
    rnd2.num[i,j]=rnd.num[i,j]*sigma*sqrt(t)+(r-0.5*sigma^2)*t
    
  }
}
#여기까지 난수 생성

rnd3.num = as.data.frame(matrix(0,s,interval))
rnd3.num[,1]=rnd2.num[,1]

for (i in 1 : s) {
  for ( j in 1 : (interval-1)) {
    rnd3.num[i,j+1] = rnd3.num[i,j]+rnd2.num[i,j+1]
    
  }
}
#여기까지 누적 x(t)   

rnd4.num = as.data.frame(matrix(0,s,interval))

for (i in 1 : s) {
  for( j in 1 : interval) {
    rnd4.num[i,j] = stock*exp(rnd3.num[i,j])
  }
}

#여기까지 주가 시뮬레이션


payoff = as.data.frame(matrix(0,s,1))
for (i in 1 : s) { 
  for(j in 1 : interval) {
    if(rnd4.num[i,j]>= barrier) {
      payoff[i,1] = 0
    }
    
    else  {
      payoff[i,1] = max(strike-rnd4.num[i,interval],0) 
      
    }
    
  }
}
#여기까지 UOP의 payoff

epv = exp(-r*0.5)*mean(payoff$V1)
#여기까지 UOP의 현가
return(epv)
}
BarrierPrice(0.03,0.2)
install.packages("derivmkts")
library(derivmkts)
putupout(stock,strike,sigma,r,0.5,0,barrier)
#여기까지 내재된 공식으로 구한 현가

PricePerR = as.data.frame(matrix(0,100,1))

for(i in 1:100) { 
  PricePerR[i,1] = BarrierPrice(i/100,0.2)
  
}

interest = as.data.frame(seq(0.01, 1, by = 0.01 ))

plot(interest$`seq(0.01, 1, by = 0.01)`, PricePerR$V1, xlab = "이자율", ylab="옵션가격", main = "이자율 변화에 따른 가격")

PricePerSigma = as.data.frame(matrix(0,10,1))

for(i in 1:10) {
  PricePerSigma[i,1] = BarrierPrice(0.03, i/10)
}

Sigma = seq(0.1,1, by = 0.1)

plot(Sigma, PricePerSigma$V1, xlab = "변동성", ylab = "옵션가격", main = "변동성에 따른 가격")
